/**
 * Web app manifest source of truth. Imported by `nuxt.config.ts` so the PWA
 * module emits this exact shape, and by unit tests so DoD fields (Phase 1.5)
 * cannot silently regress.
 *
 * Icon paths reference files generated by `pnpm pwa-assets` from
 * `public/icons/source.svg` — see `pwa-assets.config.ts`.
 */
export interface PwaManifestIcon {
  src: string;
  sizes: string;
  type: string;
  purpose?: "any" | "maskable" | "monochrome";
}

export interface PwaManifest {
  name: string;
  short_name: string;
  description: string;
  lang: string;
  start_url: string;
  scope: string;
  display: "standalone" | "fullscreen" | "minimal-ui" | "browser";
  orientation: "any" | "portrait" | "landscape";
  theme_color: string;
  background_color: string;
  icons: PwaManifestIcon[];
}

export const pwaManifest: PwaManifest = {
  name: "dbboard-web",
  short_name: "dbboard",
  description: "Browser-based multi-database client. Self-hosted OSS companion to dbboard.",
  lang: "en",
  start_url: "/",
  scope: "/",
  display: "standalone",
  orientation: "any",
  theme_color: "#2563eb",
  background_color: "#ffffff",
  icons: [
    {
      src: "/icons/pwa-192x192.png",
      sizes: "192x192",
      type: "image/png",
    },
    {
      src: "/icons/pwa-512x512.png",
      sizes: "512x512",
      type: "image/png",
    },
    {
      src: "/icons/maskable-icon-512x512.png",
      sizes: "512x512",
      type: "image/png",
      purpose: "maskable",
    },
  ],
};
